# prometheus.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'laravel'
        static_configs:
          - targets: ['laravel-service:8082']

    rule_files:
      -   rules.yml
